require 'ruby-progressbar'
require_relative 'players'

# require_relative 'add_pitcher_balks'
# require_relative 'add_pitcher_doubles'
# require_relative 'add_pitcher_hit_by_pitches'
# require_relative 'add_pitcher_homers'
# require_relative 'add_pitcher_intentional_walks'
# require_relative 'add_pitcher_outs'
# require_relative 'add_pitcher_pick_offs'
# require_relative 'add_pitcher_sacrifice_flies'
# require_relative 'add_pitcher_sacrifice_hits'
# require_relative 'add_pitcher_singles'
# require_relative 'add_pitcher_stolen_bases'
# require_relative 'add_pitcher_triples'
# require_relative 'add_pitcher_walks'
# require_relative 'add_pitcher_wild_pitches'
# require_relative 'seed_players_from_csv'
# require_relative 'add_full_name_to_players'
# require_relative 'update_players_debut_from_csv'
# require_relative 'update_players_debut_year'

require_relative 'add_batter_walks'
require_relative 'add_batter_intentional_walks'
require_relative 'add_batter_hit_by_pitches'
require_relative 'add_batter_fielders_choices'
